animal=('cat','dog','fish','lizard','bird')
listofAnimals=list(animal)
print(listofAnimals)
listofAnimals.append('hamster')
print(listofAnimals)
myString="hiya nice to meet you!"
newString=list(myString)
print(newString)
newString=myString.split(" ")
print(newString)