# Generated by Django 3.1.7 on 2021-04-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=200)),
                ('CourseNumber', models.DecimalField(decimal_places=0, max_digits=5)),
                ('Instructor', models.TextField(max_length=200)),
                ('Duration', models.TextField(max_length=4)),
            ],
        ),
    ]
